language: ruby
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.bundle
rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - jruby-head
  - rubinius-3.86
env:
  - CZMQ_VERSION=HEAD ZMQ_VERSION=stable
  - CZMQ_VERSION=stable ZMQ_VERSION=stable
matrix:
  exclude:
    - rvm: 2.3.3
      env: CZMQ_VERSION=HEAD ZMQ_VERSION=stable
    - rvm: 2.2.6
      env: CZMQ_VERSION=HEAD ZMQ_VERSION=stable
    - rvm: rubinius-3.86
      env: CZMQ_VERSION=HEAD ZMQ_VERSION=stable
  allow_failures:
    - rvm: rubinius-3.86
before_install:
  - PATH="/usr/lib/ccache:$PATH" # enable ccache
  - export LD_LIBRARY_PATH=$HOME/lib # custom libs (for execution)
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig # custom libs (for linking)
  - export BUNDLE_PATH=$HOME/.bundle # bundle caching
  - ci-scripts/install-libzmq
  - ci-scripts/install-libczmq
  - gem install bundler -v 1.10.6
script: bundle exec rake spec
