require_relative "czmq-ffi-gen/czmq/ffi"
require_relative "czmq-ffi-gen/gem_version"
require_relative "czmq-ffi-gen/library_version"
require_relative "czmq-ffi-gen/signals"
require_relative "czmq-ffi-gen/zmq_error"
CZMQ::FFI.available? or raise LoadError, "libczmq is not available"
