require_relative "czmq-ffi-gen/czmq/ffi"
require_relative "czmq-ffi-gen/versions"
require_relative "czmq-ffi-gen/errors"
require_relative "czmq-ffi-gen/signals"
require_relative "czmq-ffi-gen/legacy"
CZMQ::FFI.available? or raise LoadError, "libczmq is not available"
