#!/bin/sh -x
# vim: ft=sh
set -e

git submodule update --init -- vendor/czmq
cd vendor/czmq

case "$CZMQ_VERSION" in
"")
	echo "Using commit recorded in git submodule"
	;;
HEAD)
	echo "Using latest commit (HEAD)"
	git pull origin master
	;;
3.0)
	echo "Using latest 3.0 tag ..."
	tag=`git tag | grep -F v3.0. | sort --field-separator=. --key=3 --numeric-sort | tail -1`
	echo "Using tag: $tag"
	git pull origin master
	git checkout $tag
	;;
*)
	echo "\$CZMQ_VERSION not set."
	exit 1
esac

./autogen.sh
./configure --prefix=$HOME
make -j2
make install

# Restore the generated Ruby binding of commit recorded in git submodule vendor/czmq.
git checkout master
cd ../..
git submodule update --force -- vendor/czmq
