#!/bin/sh -x
# vim: ft=sh
set -e
mkdir -p ~/src
cd ~/src
env
ls -la $LD_LIBRARY_PATH
ls -la $LD_RUN_PATH

git clone https://github.com/zeromq/libzmq
cd libzmq
./autogen.sh
./configure --prefix=$HOME
make
make install
