#!/bin/sh -x
# vim: ft=sh
set -e

git submodule update --init -- vendor/czmq
cd vendor/czmq

case "$CZMQ_VERSION" in
"")
	echo "Using commit recorded in git submodule"
	;;
HEAD)
	echo "Using latest commit (HEAD) and compiling with --enable-drafts ..."
	git pull origin master
	CONFIGURE_OPTS="--enable-drafts=yes"
	;;
stable)
	echo "Using latest stable release ..."
	tag=`git tag | grep ^v | grep -v -- -rc | sort --field-separator=. --key=1,3 --numeric-sort | tail -1`
	echo "Using tag: $tag"
	git pull origin master
	git checkout $tag
	CONFIGURE_OPTS="--enable-drafts=no"
	;;
*)
	echo "\$CZMQ_VERSION not set."
	exit 1
esac

./autogen.sh
./configure --prefix=$HOME $CONFIGURE_OPTS
make -j2
make install

# Restore the generated Ruby binding of commit recorded in git submodule vendor/czmq.
git checkout master
cd ../..
git submodule update --force -- vendor/czmq
