#!/bin/sh -x
# vim: ft=sh
set -e
mkdir -p ~/src
cd ~/src
env

git clone https://github.com/zeromq/libzmq
cd libzmq
./autogen.sh
sodium_LIBS="-L$LD_RUN_PATH" ./configure --prefix=$HOME
make
make install
