name: Specs

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
    - name: Install CZMQ
      run: sudo apt install libczmq-dev
    - name: Check out CZMQ git submodule
      run: git submodule update --init -- vendor/czmq
    - name: Run the default task
      run: |
        gem install bundler
        bundle install
        bundle exec rake
